server:
  port: 8080
spring:
  application:
    name: seconds-kill
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    password: xuehuafeiwu
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=UTC
    username: root
    validationQuery: select 'x'

    rabbitmq:
      host: 127.0.0.1
      listener:
        simple:
          auto-startup: true
          concurrency: 10
          default-requeue-rejected: true
          max-concurrency: 10
          prefetch: 1
      password: guest
      port: 5672
      template:
        retry:
          enabled: 'true '
          initial-interval: 1000.0
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0
      username: guest
      virtual-host: /

redis:
  host: 127.0.0.1
#  password: 123456
  poolMaxIdle: 500
  poolMaxTotal: 1000
  poolMaxWait: 500
  port: 6379
  timeout: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml

